const compactData = {
    rows: [
        {
            id: 11,
            number: "SW-0001",
            takeGoods: "上海思伟软件有限公司",
            matching: "思伟软件",
            name: 'alex',
            telNumber:'12345678911',
            role:'用户',
            startDate:'2009-02-09',
            endDate:'2009-05-19',
            hour:'220',
            rule:'代签',
            message:'收货发货租赁',
            cCount:12,
            aCount:45,
            aFCount:78,
            style:'C30',
            part:'地下一层',
            code:'hello world!',
            tableName:'生产任务单',
            del: true
        }, {
            id: 2,
            number: "SW-0002",
            takeGoods: "上海思伟软件有限公司",
            matching: "思伟软件",
            name: 'jack',
            telNumber:'12345678911',
            role:'用户',
            startDate:'2003-05-09',
            endDate:'2004-05-19',
            hour:'888',
            rule:'代签',
            message:'收货发货租赁',
            cCount:12,
            aCount:45,
            aFCount:78,
            style:'C30',
            part:'地下一层',
            code:'hello world!',
            tableName:'生产任务单',
            del: true
        }, {
            id: 3,
            number: "SW-0003",
            takeGoods: "上海思伟软件有限公司",
            matching: "思伟软件",
            name: 'rose',
            telNumber:'12345678911',
            role:'管理员',
            startDate:'2016-01-09',
            endDate:'2016-09-09',
            hour:'210',
            rule:'代签',
            message:'收货发货租赁',
            cCount:12,
            aCount:45,
            aFCount:78,
            style:'C30',
            part:'地下一层',
            code:'hello world!',
            tableName:'生产任务单',
            del: true
        }, {
            id: 4,
            number: "SW-0004",
            sendGoods: "上海思伟软件有限公司",
            takeGoods: "上海思伟软件有限公司",
            matching: "思伟软件有限公司",
            name: 'jane',
            telNumber:'12345678911',
            role:'用户',
            startDate:'2016-11-09',
            endDate:'2017-01-09',
            hour:'22',
            rule:'代签',
            message:'收货发货租赁',
            cCount:12,
            aCount:45,
            aFCount:78,
            style:'C30',
            part:'地下一层',
            code:'hello world!',
            tableName:'生产任务单',
            del: true
        }, {
            id: 5,
            number: "SW-0005",
            sendGoods: "上海思伟软件有限公司",
            takeGoods: "上海思伟软件有限公司",
            matching: "思伟软件",
            name: 'vivian',
            telNumber:'12345678911',
            role:'用户',
            startDate:'2016-12-19',
            endDate:'2017-01-09',
            hour:'90',
            rule:'代签',
            message:'收货发货租赁',
            cCount:12,
            aCount:45,
            aFCount:78,
            style:'C30',
            part:'地下一层',
            code:'hello world!',
            tableName:'生产任务单',
            del: true
        }, {
            id: 6,
            number: "SW-0006",
            sendGoods: "上海思伟软件有限公司",
            takeGoods: "上海思伟软件有限公司",
            matching: "思伟软件有限公司",
            name: 'kiukiukui',
            telNumber:'12345678911',
            role:'用户',
            startDate:'2016-08-18',
            endDate:'2016-09-29',
            hour:'2',
            rule:'代签',
            message:'收货发货租赁',
            cCount:12,
            aCount:45,
            aFCount:78,
            style:'C30',
            part:'地下一层',
            code:'hello world!',
            tableName:'生产任务单',
            del: true
        }, {
            id: 7,
            number: "SW-0007",
            sendGoods: "上海思伟软件有限公司",
            takeGoods: "上海思伟软件有限公司",
            matching: "思伟软件有限公司",
            name: 'pink',
            telNumber:'12345678911',
            role:'管理员',
            startDate:'2016-06-29',
            endDate:'2016-09-04',
            hour:'60',
            rule:'代签',
            message:'收货发货租赁',
            cCount:12,
            aCount:45,
            aFCount:78,
            style:'C30',
            part:'地下一层',
            code:'hello world!',
            tableName:'生产任务单',
            del: true
        }, {
            id: 8,
            number: "SW-0008",
            sendGoods: "上海思伟软件有限公司",
            takeGoods: "上海思伟软件有限公司",
            matching: "思伟软件",
            name: 'tom',
            telNumber:'12345678911',
            role:'用户',
            startDate:'2016-03-16',
            endDate:'2016-06-29',
            hour:'78',
            rule:'代签',
            message:'收货发货租赁',
            cCount:12,
            aCount:45,
            aFCount:78,
            style:'C30',
            part:'地下一层',
            code:'hello world!',
            tableName:'生产任务单',
            del: true
        }, {
            id: 9,
            number: "SW-0009",
            sendGoods: "上海思伟软件有限公司",
            takeGoods: "上海思伟软件有限公司",
            matching: "思伟软件有限公司",
            name: 'joly',
            telNumber:'12345678911',
            role:'用户',
            startDate:'2016-10-21',
            endDate:'2016-12-12',
            hour:'87',
            rule:'代签',
            message:'收货发货租赁',
            cCount:12,
            aCount:45,
            aFCount:78,
            style:'C30',
            part:'地下一层',
            code:'hello world!',
            tableName:'生产任务单',
            del: true
        }
    ]
};

export default compactData;
