/**
 * Created by SWSD on 2017-01-06.
 */

// 车辆管理    begin-=========

export const LOAD_CARS_ITEMS='LOAD_CARS_ITEMS';
export const GET_CARS_ITEMS='GET_CARS_ITEMS';

export const CAR_BREAKDOWN_STATE='CAR_BREAKDOWN_STATE';
export const CAR_FREE_STATE='CAR_FREE_STATE';
export const CAR_WORK_STATE='CAR_WORK_STATE';
export const SEARCH_COMPANY='SEARCH_COMPANY';
export const FILTER_BRKDWN='FILTER_BRKDWN';


//车辆管理==end=====


//匹配
export const TOGGLE_MATCHING_MODEL='TOGGLE_MATCHING_MODEL';
export const CLOSE_MATCHING_MODEL='CLOSE_MATCHING_MODEL';
export const CLICK_MATCHING_DETAIL='CLICK_MATCHING_DETAIL';
export const SHOW_MATCHING_USERMODEL='SHOW_MATCHING_USERMODEL';
export const SHOW_MATCHING_USERMODEL2='SHOW_MATCHING_USERMODEL2';
export const SHOW_MATCHING_COMPANYLIST='SHOW_MATCHING_COMPANYLIST';
export const CLOSE_MATCHING_FIRSTCOMPANYLIST='CLOSE_MATCHING_FIRSTCOMPANYLIST';
export const SHOW_REGISTER_USERDEATIL='SHOW_REGISTER_USERDEATIL';
export const CLOSE_REGISTER_USERDEATIL='CLOSE_REGISTER_USERDEATIL';
export const GET_MATCHINGDATA='GET_MATCHINGDATA';


//发货管理
export const TOGGLE_SENDGOODSMODAL='TOGGLE_SENDGOODSMODAL';
export const CLOSE_SENDGOODSMODAL='CLOSE_SENDGOODSMODAL';
export const GET_RIGHTKEYID='GET_RIGHTKEYID';
export const SHOW_COMPACTDETAIL='SHOW_COMPACTDETAIL';
export const CLOSE_COMPACTDETAIL='CLOSE_COMPACTDETAIL';
export const SHOW_TASKDETAIL='SHOW_TASKDETAIL';
export const CLOSE_TASKDETAIL='CLOSE_TASKDETAIL';
export const SHOW_TRANSPORTDETAIL='SHOW_TRANSPORTDETAIL';
export const CLOSE_TRANSPORTDETAIL='CLOSE_TRANSPORTDETAIL';
export const GET_COMPANYLISTDATAS='GET_COMPANYLISTDATAS';
export const GET_S_OPERATION='GET_S_OPERATION';

//故障详情model 的UI状态
export const GET_BRKDWN_DETAIL='GET_BRKDWN_DETAIL';


//统计===
export const TOGGLE_DAY='TOGGLE_DAY';
export const TOGGLE_WEEK='TOGGLE_WEEK';
export const TOGGLE_SEASON='TOGGLE_SEASON';
export const TOGGLE_YEAR='TOGGLE_YEAR';

//内部用户管理

//头部
export const LOGIN_OUT='LOGIN_OUT';
export const LOGIN_IN='LOGIN_IN';
export const GET_HEADER_INFO='GET_HEADER_INFO';
//高级搜索
export const GET_MENU_INDEX='GET_menuIndex';
export const HIGHTLIGHT_REG='HIGHTLIGHT_REG';
export const SET_TAB='SET_TAB';


//合同
export const TOGGLE_COMPACT_MODEL='TOGGLE_COMPACT_MODEL';
export const TOGGLE_LEASECOMPACT_MODEL='TOGGLE_LEASECOMPACT_MODEL';

//发货单位管理
export const TOGGLE_ADD_SEND='TOGGLE_ADD_SEND';
export const TOGGLE_MAP='TOGGLE_MAP';
export const SELECT_SEND='SELECT_SEND';
export const TOGGLE_SEND_CONFIG='TOGGLE_SEND_CONFIG';
export const TOGGLE_SEND_SELFCAR='TOGGLE_SEND_SELFCAR';
export const ISCOMPANYINPUT_BLOCK='ISCOMPANYINPUT_BLOCK';
export const GET_SEND_UNIT='GET_SEND_UNIT';


//首页
const SEVER_ROOT='http://192.168.1.67:8889/';
export default  SEVER_ROOT;
export const GET_PREVIEW_PIC='GET_PREVIEW_PIC';
export const CLEAR_PREIMGURL='CLEAR_PREIMGURL';
export const INDEX_INIT='INDEX_INIT';//首页初始化
export const INDEX_CART='INDEX_CART';//首页数据曲线请求
export const INDEX_FEEDBACK='INDEX_FEEDBACK';//首页反馈信息
export const INDEX_NOTICE='INDEX_NOTICE';//首页系统公告信息

